// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import AddToCartButton from './AddToCartButton.vue'
import Cart from './Cart.vue'
import CartItem from './CartItem.vue'

import cart from './api/cart.js'
import cartItem from './api/cartItem.js'

// Export components individually
export { AddToCartButton, Cart, CartItem, cart, cartItem }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('AddToCartButton', AddToCartButton)
  Vue.component('Cart', Cart)
  Vue.component('CartItem', CartItem)
}

// Export the library as a plugin
export default { install: install }
